name: Autograding

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install pytest
    - name: Run tests
      run: |
        echo "Running visible tests..."
        pytest tests/test_visible.py

        echo "Running hidden tests..."
        if [ -f tests/test_hidden.py ]; then
          pytest tests/test_hidden.py
        else
          echo "No hidden tests found in student repos."
        fi
